### ISSUE TITLE
TypeError at BigInteger

### ISSUE THREAD

**Issue by Christilut** [andyperlitch/jsbn#6]
Made a tiny test case:

``` javascript
BigInteger = require('jsbn')

p1 = new BigInteger('100', 100)

console.log(p1)
```

which results in

```
p1 = new BigInteger('100', 100)
     ^
TypeError: object is not a function
    at Object.<anonymous> (C:\Users\codes\OneDrive\Projects\test\index.js:8:6)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I originally encountered this error in [Meteor Up](https://github.com/arunoda/meteor-up) after doing an update.

I fixed it temporarily by changing

``` js
    if (typeof exports !== 'undefined') {
      exports = module.exports = {
        BigInteger: BigInteger,
        SecureRandom: SecureRandom,
      };
    } else {
        this.BigInteger = BigInteger;
        this.SecureRandom = SecureRandom;
    }
```

to

``` js
    if (typeof exports !== 'undefined') {
        exports = module.exports = BigInteger;
    } else {
        this.BigInteger = BigInteger;
    }
```

which I took from version 0.0.0 after noticing that version 0.0.0 didn't cause the above error.

Obviously not a good fix since now SecureRandom will be undefined so that needs fixing.

**Comment by darlanalves** [comment]
This is due to https://github.com/andyperlitch/jsbn/commit/72f1a24486f8d4d4e895a9fdd9e34a3d66f9f90b
added back on January.

This export syntax should be kept, in my opinion, as it goes well with ES6 as well:
```js
import { BigInteger } from 'jsbn';
```

I faced the same problem earlier this month and forked the libraries that depend on this lib.
This is a breaking change, so just a version bump should be enough.

@andyperlitch would you publish a new version on npm, please?

**Comment by andyperlitch** [comment]
`v0.1.1` has just been published with the fix for the backwards-compatibility issue. Apologies for the lag.
